### ISSUE TITLE
Failed to resolve entry for package "@zakerxa/vue-multiple-image-upload". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

### ISSUE THREAD

**Issue by limweebeng** [Zakerxa/Vue-Multi-Image-Upload#5]
I tried the component in the latest vue framework (with vite). However, it is unable to be compiled due to the following reason.

Failed to resolve entry for package "@zakerxa/vue-multiple-image-upload". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/vite/node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
    at tryNodeResolve (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at Object.resolveId (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43145:26)
    at async file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43322:34
    at async requestCallbacks.on-resolve (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:1360:22)
    at async handleRequest (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:723:13)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43312:19)
    at handlePlugins (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:1279:21)
    at buildOrContextImpl (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:968:5)
    at Object.buildOrContext (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:776:5)
    at C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:2172:27)
    at Object.context (C:\limsheryl2\node_modules\vite\node_modules\esbuild\lib\main.js:2012:58)
    at prepareEsbuildScanner (file:///C:/limsheryl2/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43097:26)

  The plugin "vite:dep-scan" was triggered by this import

**Comment by scoroop** [comment]
same here. not usable at the moment.

**Comment by aptaganteng** [comment]
package doesnt include esm.js
